### ISSUE TITLE
Support  --init param or --local

### ISSUE THREAD

**Issue by vrutkovs** [Containers-Testing-Framework/ctf-cli#2]
In order to be flexible ctf-cli should support `--init` param to generate initial dir structure. 

That would allow local runs using simple `behave` invocation (local tests for developers, CI systems like CircleCI). If `ctf-cli` is invoked it should use ansible params specified in `ctf.conf`

**Comment by vrutkovs** [comment]
Another option is to support `sudo` ansible playbook

**Comment by thozza** [comment]
I was thinking of redefining the CLI to use commands, rather options for that. Something like:

```
# ctf-cli prep
# ctf-cli run
# ctf-cli update
```

and still be able to pass some arguments like path to the configuration. What do you think? It kind of mimics the fedpkg/rhpkg approach which I find pretty friendly.

**Comment by thozza** [comment]
also if nothing is passed, just assume the current functionality and do all the steps.
