### ISSUE TITLE
Don't store sample environment.py as a text

### ISSUE THREAD

**Issue by vrutkovs** [Containers-Testing-Framework/ctf-cli#3]
We should store common_environment.py as a normal file and copy it to work dir

**Comment by thozza** [comment]
right. I just wasn't sure how it will work once the ctf-cli would be e.g. installed in the system from RPM or using pip. But I'm all for it. it was the easiest approach without need for further testing ;)

**Comment by vrutkovs** [comment]
Changes in #12 affect common_environment, lets wait for it get merged before fixing this

**Comment by rwngwn** [comment]
@thozza it can work. you can get path to file from inspecting that module and copy it.

**Comment by vrutkovs** [comment]
Fixed in #35
