### ISSUE TITLE
Make `-f` argument optional

### ISSUE THREAD

**Issue by jmtd** [Containers-Testing-Framework/ctf-cli#33]
Hi! We're using `ctf-cli` for a fairly large repository of dockerfiles and related stuff. We want to invoke CTF in two different ways: via hooks in our CI, but also by hand. When run by hand, we just want to test a particular image, already built, with a particular set of tests/features.

We've written a quick wrapper script around `ctf-cli` that gives us this interface<sup>[1](https://github.com/l-d-j/ce-ctf-tests/commit/de71ebf210af30acc9a935fbb02d77b07f47b0cb)</sup>.

One of the things we don't need for this approach is to specify the dockerfile, however it is mandatory in `ctf-cli` at the moment.  As you can see in the wrapper, we can get around this at the moment by just specifying `/dev/null`, but it would be nicer if it wasn't mandated.

I've started working on fixes for this<sup>[2](https://github.com/Containers-Testing-Framework/ctf-cli/commit/d3044fee1f6fe513af0a73e7c39c477e2c4cdef8)</sup> but there's nothing worth submitting a PR for yet.

**Comment by jmtd** [comment]
Just a bit more on our repository structure: We do not have a top-level Dockerfile, we have categories of image types, with shared tests/features, arranged a bit like this

```
webserver/webservers.feature
webserver/type1/versionX/Dockerfile
webserver/type1/type1.feature
webserver/type2/versionY/Dockerfile
...
```

So we also don't have all the tests in a separate directory structure. Some tests apply to multiple images, e.g. `webservers.feature` in the above example to both of the images described; but `type1.feature` only to the type1 image.

**Comment by vrutkovs** [comment]
Agreed, we shouldn't really require Dockerfile
