### ISSUE TITLE
Use CircleCI to verify ctf-cli changes

### ISSUE THREAD

**Issue by vrutkovs** [Containers-Testing-Framework/ctf-cli#34]
https://github.com/vrutkovs/mysql/tree/ctf-cli-circleci uses ctf-cli to run tests. At this point the tests are stable, so we can reuse them to make sure that ctf-cli changes didn't break anything.

Ideally we should do the following:
- Create a new repo for testing
- In ctf-cli's `circleci.yml` clone it, run `ctf-cli init`
- Reset to HEAD^ for common steps/features and run `ctf-cli update`
- Do `ctf-cli run` and check that common steps/features run correctly.

NTH: 
- coverage reports
- Copy this to common steps/features repos

**Comment by thozza** [comment]
We should be running also unit tests from https://github.com/Containers-Testing-Framework/ctf-cli/tree/master/test
