### ISSUE TITLE
Store commit id in tests.conf

### ISSUE THREAD

**Issue by vrutkovs** [Containers-Testing-Framework/ctf-cli#4]
We shouldn't assume that `common-steps` or `common-features` will be API stable. Instead, we should set `Commit` field for each repo.

When test is started specified commit should be checked out. `ctf-cli` should have an option to pull latest changes via `--update-submodules` command. If no commit id is specified in `tests.conf` configuration file should be updated with latest fetched commit.

**Comment by vrutkovs** [comment]
This is mostly superseded by #12 - we don't need tests.conf at all

**Comment by thozza** [comment]
We will not use tests.conf in the future as it is used today, thus this functionality will not be needed
