### ISSUE TITLE
Provide functions to be reused in custom environment.py

### ISSUE THREAD

**Issue by goldmann** [Containers-Testing-Framework/ctf-cli#45]
You currently pull the image no matter if it's already available locally or not. This needs to be made optional, because when we build our images - our local images are newer and pulling the same image will re-tag it and our tests will be run on old image. And of course we waste the time to request the image, etc.

Side note: This would not be a problem if I could easily override stuff from [common_environment_content.py](https://github.com/Containers-Testing-Framework/ctf-cli/blob/master/ctf_cli/common_environment_content.py) in my custom `environment.py` file. Stuff like [this](https://github.com/Containers-Testing-Framework/ctf-cli/blob/master/ctf_cli/behave.py#L266-L286) makes it very hard and just looks ugly and hacky.

/cc @l-d-j

**Comment by goldmann** [comment]
Idea: Instead of rewriting .py files - let us control how we want to create environment. We could import the `common_environment.py` but only if we want. All methods in there should be split and be easy to reuse.

**Comment by vrutkovs** [comment]
Agreed, we should be giving users a list of functions they can reuse (and rearrange to their preference) in `environment.py`, e.g.

```
from common_docker_environment import remove_containers, remove_cid_file

def after_scenario(context, scenario):
      remove_containers()
      # some custom code goes here
      remove_cid_file()
```
