### ISSUE TITLE
Upgrade to use Ansible 2

### ISSUE THREAD

**Issue by goldmann** [Containers-Testing-Framework/ctf-cli#64]
Currently this tool requires Ansible 1.9, which is old, we should upgrade to latest Ansible version.

**Comment by vrutkovs** [comment]
This is resolved by https://github.com/Containers-Testing-Framework/common-steps/commit/db8851475e82c9cefb2bf822d1309cdb42970662 and https://github.com/Containers-Testing-Framework/ctf-cli/commit/5a0758d6d85e05991f6d88b6480f126e05d6cc00

Mysql tests worked: https://github.com/Containers-Testing-Framework/example-project-mysql/commit/0d4202dacdefb6a4be3d388041fc35754a2e61ec, however some corner cases might fail - don't stop filing those issues!

**Comment by goldmann** [comment]
Yay, thanks! I'll give it a shot on Monday!
